controllers:
    resource: ../src/Controller/
    type: attribute

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

list-employees:
     path:/employees
     controller:App\controller\employeescontroller::employees
